import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import { getModelToken } from '@nestjs/mongoose';

const categories = [
  { name: 'Грудь', emoji: '💪', description: 'Верхняя часть тела — грудные мышцы', sortOrder: 1 },
  { name: 'Спина', emoji: '🔙', description: 'Широчайшие, трапеции, разгибатели', sortOrder: 2 },
  { name: 'Ноги', emoji: '🦵', description: 'Квадрицепсы, бицепс бедра, ягодицы, икры', sortOrder: 3 },
  { name: 'Плечи', emoji: '🏋️', description: 'Дельтовидные мышцы и трапеции', sortOrder: 4 },
  { name: 'Руки', emoji: '💪', description: 'Бицепс, трицепс, предплечья', sortOrder: 5 },
  { name: 'Пресс', emoji: '🔥', description: 'Мышцы кора и стабилизаторы', sortOrder: 6 },
  { name: 'Кардио', emoji: '❤️', description: 'Выносливость и сжигание калорий', sortOrder: 7 },
];

// GIF URLs — используются проверенные источники wger.de (open source)
// Если GIF не загрузится, на фронте есть onError fallback

const exercisesByCategory: Record<string, any[]> = {
  'Грудь': [
    {
      name: 'Жим штанги лёжа',
      description: 'Король упражнений на грудь. Развивает массу и силу грудных мышц, передних дельт и трицепсов.',
      gifUrl: 'https://static.wger.de/media/exercise-images/192/Barbell-bench-press-1.png',
      type: 'strength',
      metValue: 6.0,
      muscleGroups: ['Большая грудная', 'Трицепс', 'Передняя дельта'],
      difficulty: 'intermediate',
      equipment: 'Штанга, скамья',
      defaultSets: 4,
      defaultReps: 10,
    },
    {
      name: 'Жим гантелей лёжа',
      description: 'Большая амплитуда движения по сравнению со штангой. Хорошо растягивает грудные мышцы.',
      gifUrl: 'https://static.wger.de/media/exercise-images/193/Dumbbell-bench-press-1.png',
      type: 'strength',
      metValue: 5.5,
      muscleGroups: ['Большая грудная', 'Трицепс', 'Передняя дельта'],
      difficulty: 'beginner',
      equipment: 'Гантели, скамья',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Разведение гантелей лёжа',
      description: 'Изолирующее упражнение для растяжки и проработки грудных мышц.',
      gifUrl: 'https://static.wger.de/media/exercise-images/195/Dumbbell-flyes-1.png',
      type: 'strength',
      metValue: 4.5,
      muscleGroups: ['Большая грудная'],
      difficulty: 'beginner',
      equipment: 'Гантели, скамья',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Отжимания',
      description: 'Упор лёжа: ладони чуть шире плеч, тело — прямая линия от макушки до пяток, пресс и ягодицы напряжены. На вдохе согните руки и опустите грудь почти до пола, локти под углом ~45° к корпусу. На выдохе мощно выжмите себя вверх. Не прогибайте поясницу и не задирайте таз. Если тяжело — отжимайтесь с колен, техника та же.',
      gifUrl: 'https://static.wger.de/media/exercise-images/182/Push-ups-1.png',
      type: 'strength',
      metValue: 8.0,
      muscleGroups: ['Большая грудная', 'Трицепс', 'Передняя дельта', 'Пресс'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Сведение рук в кроссовере',
      description: 'Изолирующее упражнение. Постоянное напряжение на протяжении всей амплитуды.',
      gifUrl: 'https://static.wger.de/media/exercise-images/98/Cable-crossover-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Большая грудная'],
      difficulty: 'intermediate',
      equipment: 'Кроссовер',
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Отжимания на брусьях',
      description: 'Отличное упражнение для нижней части груди и трицепсов.',
      gifUrl: 'https://static.wger.de/media/exercise-images/196/Dips-1.png',
      type: 'strength',
      metValue: 7.0,
      muscleGroups: ['Нижняя грудная', 'Трицепс', 'Передняя дельта'],
      difficulty: 'intermediate',
      equipment: 'Брусья',
      defaultSets: 3,
      defaultReps: 10,
    },
  ],

  'Спина': [
    {
      name: 'Подтягивания широким хватом',
      description: 'Лучшее упражнение для развития широчайших мышц спины и V-образного силуэта.',
      gifUrl: 'https://static.wger.de/media/exercise-images/194/Pull-ups-1.png',
      type: 'strength',
      metValue: 8.0,
      muscleGroups: ['Широчайшие', 'Большая круглая', 'Бицепс'],
      difficulty: 'intermediate',
      equipment: 'Турник',
      defaultSets: 4,
      defaultReps: 8,
    },
    {
      name: 'Тяга штанги в наклоне',
      description: 'Базовое упражнение для толщины спины. Прорабатывает среднюю часть трапеций и ромбовидные.',
      gifUrl: 'https://static.wger.de/media/exercise-images/142/Barbell-bent-over-row-1.png',
      type: 'strength',
      metValue: 6.0,
      muscleGroups: ['Широчайшие', 'Трапеция', 'Ромбовидные', 'Бицепс'],
      difficulty: 'intermediate',
      equipment: 'Штанга',
      defaultSets: 4,
      defaultReps: 10,
    },
    {
      name: 'Тяга гантели в наклоне',
      description: 'Односторонняя тяга позволяет лучше концентрироваться на каждой стороне спины.',
      gifUrl: 'https://static.wger.de/media/exercise-images/214/Dumbbell-bent-over-row-1.png',
      type: 'strength',
      metValue: 5.5,
      muscleGroups: ['Широчайшие', 'Трапеция', 'Бицепс'],
      difficulty: 'beginner',
      equipment: 'Гантель, скамья',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Тяга верхнего блока',
      description: 'Альтернатива подтягиваниям для начинающих. Хорошо прорабатывает широчайшие.',
      gifUrl: 'https://static.wger.de/media/exercise-images/133/Lat-pulldown-1.png',
      type: 'strength',
      metValue: 5.0,
      muscleGroups: ['Широчайшие', 'Бицепс'],
      difficulty: 'beginner',
      equipment: 'Тренажёр',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Тяга горизонтального блока',
      description: 'Прорабатывает среднюю часть спины. Укрепляет осанку.',
      gifUrl: 'https://static.wger.de/media/exercise-images/134/Seated-cable-row-1.png',
      type: 'strength',
      metValue: 5.0,
      muscleGroups: ['Широчайшие', 'Трапеция', 'Ромбовидные'],
      difficulty: 'beginner',
      equipment: 'Тренажёр',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Становая тяга',
      description: 'Комплексное упражнение для всей задней цепи. Основа силовой подготовки.',
      gifUrl: 'https://static.wger.de/media/exercise-images/151/Deadlift-1.png',
      type: 'strength',
      metValue: 7.0,
      muscleGroups: ['Разгибатели спины', 'Ягодицы', 'Бицепс бедра', 'Трапеция'],
      difficulty: 'advanced',
      equipment: 'Штанга',
      defaultSets: 4,
      defaultReps: 6,
    },
  ],

  'Ноги': [
    {
      name: 'Приседания без веса',
      description: 'Ноги на ширине плеч, носки слегка развёрнуты, руки вперёд для баланса. На вдохе отведите таз назад и присядьте до параллели бёдер с полом (как на невидимый стул): спина прямая, пятки прижаты, колени идут за носками и не заваливаются внутрь. На выдохе встаньте, толкаясь пятками и сжимая ягодицы в верхней точке. Вниз — медленно, вверх — мощно.',
      gifUrl: 'pending',
      type: 'strength',
      metValue: 5.0,
      muscleGroups: ['Квадрицепс', 'Ягодичные', 'Кор'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 4,
      defaultReps: 15,
      defaultDurationSec: null,
    },
    {
      name: 'Ягодичный мостик',
      description: 'Лягте на спину, колени согнуты, стопы на полу на ширине таза, пятки близко к ягодицам, руки вдоль тела. На выдохе, толкаясь пятками, поднимите таз до прямой линии «колени—таз—плечи» и сожмите ягодицы на 1–2 секунды в верхней точке. На вдохе плавно опуститесь, не касаясь тазом пола до конца сета. Не прогибайте поясницу — подъём только за счёт ягодиц.',
      gifUrl: 'pending',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Ягодичные', 'Бицепс бедра', 'Кор'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 4,
      defaultReps: 15,
      defaultDurationSec: null,
    },
    {
      name: 'Приседания со штангой',
      description: 'Король упражнений для ног. Развивает квадрицепсы, ягодицы и укрепляет всё тело.',
      gifUrl: 'https://static.wger.de/media/exercise-images/106/Barbell-squat-1.png',
      type: 'strength',
      metValue: 6.0,
      muscleGroups: ['Квадрицепс', 'Ягодичные', 'Кор', 'Бицепс бедра'],
      difficulty: 'intermediate',
      equipment: 'Штанга, стойка',
      defaultSets: 4,
      defaultReps: 10,
    },
    {
      name: 'Выпады с гантелями',
      description: 'Встаньте прямо, руки с гантелями (или без) вдоль тела. Шагните одной ногой вперёд и опуститесь, пока оба колена не согнутся до ~90°: заднее колено почти касается пола, переднее не выходит за носок. Оттолкнитесь передней пяткой и вернитесь в стойку. Корпус держите вертикально, взгляд вперёд. Чередуйте ноги; повторения считаются на каждую ногу.',
      gifUrl: 'https://static.wger.de/media/exercise-images/197/Dumbbell-lunges-1.png',
      type: 'strength',
      metValue: 5.0,
      muscleGroups: ['Квадрицепс', 'Ягодичные'],
      difficulty: 'beginner',
      equipment: 'Гантели',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Жим ногами',
      description: 'Безопасная альтернатива приседаниям в тренажёре. Позволяет работать с большим весом.',
      gifUrl: 'https://static.wger.de/media/exercise-images/118/Leg-press-1.png',
      type: 'strength',
      metValue: 5.0,
      muscleGroups: ['Квадрицепс', 'Ягодичные'],
      difficulty: 'beginner',
      equipment: 'Тренажёр',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Румынская тяга',
      description: 'Лучшее упражнение для задней поверхности бедра и ягодиц.',
      gifUrl: 'https://static.wger.de/media/exercise-images/152/Romanian-deadlift-1.png',
      type: 'strength',
      metValue: 6.0,
      muscleGroups: ['Бицепс бедра', 'Ягодичные', 'Разгибатели спины'],
      difficulty: 'intermediate',
      equipment: 'Штанга',
      defaultSets: 3,
      defaultReps: 10,
    },
    {
      name: 'Разгибания ног в тренажёре',
      description: 'Изолирующее упражнение для квадрицепсов. Хорошо для разминки или добивки.',
      gifUrl: 'https://static.wger.de/media/exercise-images/119/Leg-extensions-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Квадрицепс'],
      difficulty: 'beginner',
      equipment: 'Тренажёр',
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Сгибания ног в тренажёре',
      description: 'Изолирующее упражнение для бицепса бедра.',
      gifUrl: 'https://static.wger.de/media/exercise-images/120/Leg-curls-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Бицепс бедра'],
      difficulty: 'beginner',
      equipment: 'Тренажёр',
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Подъёмы на носки',
      description: 'Проработка икроножных мышц. Важно не забывать про ноги полностью.',
      gifUrl: 'https://static.wger.de/media/exercise-images/139/Calves-1.png',
      type: 'strength',
      metValue: 3.5,
      muscleGroups: ['Икроножная', 'Камбаловидная'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 4,
      defaultReps: 20,
    },
  ],

  'Плечи': [
    {
      name: 'Жим гантелей стоя',
      description: 'Базовое упражнение для развития всех трёх пучков дельтовидных мышц.',
      gifUrl: 'https://static.wger.de/media/exercise-images/193/Dumbbell-shoulder-press-1.png',
      type: 'strength',
      metValue: 6.0,
      muscleGroups: ['Передняя дельта', 'Средняя дельта', 'Трицепс'],
      difficulty: 'intermediate',
      equipment: 'Гантели',
      defaultSets: 4,
      defaultReps: 10,
    },
    {
      name: 'Разведение гантелей в стороны',
      description: 'Изолирующее упражнение для средней дельты. Формирует ширину плеч.',
      gifUrl: 'https://static.wger.de/media/exercise-images/201/Lateral-raise-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Средняя дельта'],
      difficulty: 'beginner',
      equipment: 'Гантели',
      defaultSets: 4,
      defaultReps: 15,
    },
    {
      name: 'Тяга гантелей к подбородку',
      description: 'Прорабатывает среднюю дельту и трапеции. Улучшает форму плеч.',
      gifUrl: 'https://static.wger.de/media/exercise-images/153/Upright-row-1.png',
      type: 'strength',
      metValue: 5.0,
      muscleGroups: ['Средняя дельта', 'Трапеция'],
      difficulty: 'intermediate',
      equipment: 'Гантели',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Махи гантелей в наклоне',
      description: 'Проработка задней дельты. Важна для баланса и осанки.',
      gifUrl: 'https://static.wger.de/media/exercise-images/202/Rear-delt-fly-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Задняя дельта', 'Трапеция'],
      difficulty: 'beginner',
      equipment: 'Гантели',
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Жим Арнольда',
      description: 'Комбинированное упражнение для всех пучков дельт. Названо в честь Арнольда Шварценеггера.',
      gifUrl: 'https://static.wger.de/media/exercise-images/193/Dumbbell-shoulder-press-1.png',
      type: 'strength',
      metValue: 6.0,
      muscleGroups: ['Передняя дельта', 'Средняя дельта'],
      difficulty: 'intermediate',
      equipment: 'Гантели',
      defaultSets: 3,
      defaultReps: 10,
    },
  ],

  'Руки': [
    {
      name: 'Сгибания рук со штангой стоя',
      description: 'Классическое упражнение для развития бицепса. Основа тренировки рук.',
      gifUrl: 'https://static.wger.de/media/exercise-images/163/Barbell-curl-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Бицепс', 'Плечевая'],
      difficulty: 'beginner',
      equipment: 'Штанга',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Молотковые сгибания',
      description: 'Прорабатывает бицепс и плечевую мышцу. Придаёт рукам объём.',
      gifUrl: 'https://static.wger.de/media/exercise-images/167/Hammer-curl-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Бицепс', 'Плечевая', 'Плечелучевая'],
      difficulty: 'beginner',
      equipment: 'Гантели',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Французский жим',
      description: 'Лучшее упражнение для длинной головки трицепса. Развивает объём рук.',
      gifUrl: 'https://static.wger.de/media/exercise-images/165/French-press-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Трицепс'],
      difficulty: 'intermediate',
      equipment: 'Штанга EZ, скамья',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Разгибания на трицепс на блоке',
      description: 'Изолирующее упражнение для проработки формы трицепса.',
      gifUrl: 'https://static.wger.de/media/exercise-images/169/Tricep-pushdown-1.png',
      type: 'strength',
      metValue: 3.5,
      muscleGroups: ['Трицепс'],
      difficulty: 'beginner',
      equipment: 'Кроссовер',
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Сгибания рук с гантелями на скамье',
      description: 'Концентрированные сгибания для пикового сокращения бицепса.',
      gifUrl: 'https://static.wger.de/media/exercise-images/164/Incline-dumbbell-curl-1.png',
      type: 'strength',
      metValue: 3.5,
      muscleGroups: ['Бицепс'],
      difficulty: 'beginner',
      equipment: 'Гантели, наклонная скамья',
      defaultSets: 3,
      defaultReps: 12,
    },
    {
      name: 'Отжимания узким хватом',
      description: 'Упражнение на трицепс с собственным весом. Развивает силу и массу.',
      gifUrl: 'https://static.wger.de/media/exercise-images/182/Push-ups-1.png',
      type: 'strength',
      metValue: 7.0,
      muscleGroups: ['Трицепс', 'Грудь'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 12,
    },
  ],

  'Пресс': [
    {
      name: 'Скручивания на полу',
      description: 'Лягте на спину, колени согнуты, стопы на полу, руки за головой или скрещены на груди. На выдохе оторвите лопатки от пола, скручивая корпус к тазу за счёт пресса — поясница остаётся прижатой. На вдохе плавно опуститесь. Не тяните себя руками за шею и не отрывайте поясницу: амплитуда небольшая, работает именно живот.',
      gifUrl: 'https://static.wger.de/media/exercise-images/91/Crunches-1.png',
      type: 'strength',
      metValue: 3.8,
      muscleGroups: ['Прямая мышца живота'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 20,
    },
    {
      name: 'Планка',
      description: 'Упор на предплечья (локти строго под плечами) и носки. Тело — одна прямая линия: подтяните живот, сожмите ягодицы, не задирайте и не роняйте таз. Смотрите в пол, шея нейтральна, дышите ровно. Держите заданное время; как только поясница начинает провисать — сет закончен. Проще вариант — планка с колен.',
      gifUrl: 'https://static.wger.de/media/exercise-images/105/Plank-1.png',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Пресс', 'Поперечная мышца', 'Кор'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 1,
      defaultDurationSec: 60,
    },
    {
      name: 'Подъём ног лёжа',
      description: 'Лягте на спину, руки вдоль тела ладонями вниз (можно под таз), ноги почти прямые. На выдохе поднимите ноги до вертикали, не отрывая поясницу от пола. На вдохе медленно опустите — в идеале не касаясь пятками пола до конца сета. Чем медленнее опускание, тем сильнее работает низ живота. Если поясница отрывается — сгибайте колени сильнее.',
      gifUrl: 'https://static.wger.de/media/exercise-images/107/Lying-leg-raise-1.png',
      type: 'strength',
      metValue: 4.5,
      muscleGroups: ['Нижний пресс', 'Подвздошно-поясничная'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Русские скручивания',
      description: 'Сядьте на пол, колени согнуты, отклоните прямую спину назад до ~45° и оторвите стопы (проще — держите пятки на полу). Сложите руки перед грудью и поворачивайте корпус вправо-влево, касаясь руками пола у бедра. Поворот идёт от талии, а не от рук; таз неподвижен. Один поворот в сторону = одно повторение. Для усложнения возьмите бутылку воды.',
      gifUrl: 'https://static.wger.de/media/exercise-images/226/Russian-twist-1.png',
      type: 'strength',
      metValue: 4.5,
      muscleGroups: ['Косые мышцы', 'Прямая мышца'],
      difficulty: 'intermediate',
      equipment: null,
      defaultSets: 3,
      defaultReps: 20,
    },
    {
      name: 'Велосипед',
      description: 'Лягте на спину, руки за головой, ноги подняты, колени согнуты под 90°. Поочерёдно тянитесь локтем к противоположному колену, одновременно выпрямляя вторую ногу над полом — как будто крутите педали. Скручивайтесь корпусом, а не дёргайте шею; поясница прижата. Темп средний, движение непрерывное. Пара «локоть-колено» = одно повторение.',
      gifUrl: 'https://static.wger.de/media/exercise-images/92/Bicycle-crunches-1.png',
      type: 'strength',
      metValue: 5.0,
      muscleGroups: ['Пресс', 'Косые мышцы'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 20,
    },
    {
      name: 'Подъём ног в висе',
      description: 'Продвинутое упражнение для сильного пресса. Требует турник.',
      gifUrl: 'https://static.wger.de/media/exercise-images/107/Hanging-leg-raise-1.png',
      type: 'strength',
      metValue: 5.0,
      muscleGroups: ['Нижний пресс', 'Кор'],
      difficulty: 'advanced',
      equipment: 'Турник',
      defaultSets: 3,
      defaultReps: 10,
    },
    {
      name: 'Обратные скручивания',
      description: 'Лягте на спину, руки вдоль тела ладонями вниз, ноги согнуты, голени параллельны полу. На выдохе подтяните колени к груди, отрывая таз от пола за счёт нижнего пресса, — движение короткое, без раскачки. На вдохе подконтрольно верните таз и бёдра обратно, не опуская стопы на пол. Не отталкивайтесь руками и не забрасывайте ноги по инерции: чем медленнее, тем эффективнее.',
      gifUrl: 'pending',
      type: 'strength',
      metValue: 4.0,
      muscleGroups: ['Нижний пресс', 'Кор'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Ножницы',
      description: 'Лягте на спину, руки вдоль тела или под тазом, прямые ноги подняты на 20–30 см над полом. Поочерёдно скрещивайте и разводите ноги в горизонтальной плоскости небольшими быстрыми движениями, держа их на весу весь сет. Поясница прижата к полу, шея расслаблена, дыхание ровное. Если поясница отрывается — поднимите ноги выше или сократите время.',
      gifUrl: 'pending',
      type: 'strength',
      metValue: 4.5,
      muscleGroups: ['Нижний пресс', 'Кор', 'Сгибатели бедра'],
      difficulty: 'intermediate',
      equipment: null,
      defaultSets: 3,
      defaultReps: 20,
    },
    {
      name: 'Подъём согнутых ног лёжа',
      description: 'Упрощённый вариант подъёма ног: лягте на спину, руки вдоль тела, ноги согнуты в коленях под 90°. На выдохе подтяните колени к груди, на вдохе медленно верните голени в исходное, не касаясь пятками пола. Поясница всё время прижата. Освоите 3×15 без потери техники — переходите к подъёму прямых ног.',
      gifUrl: 'pending',
      type: 'strength',
      metValue: 3.8,
      muscleGroups: ['Нижний пресс', 'Кор'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 15,
    },
    {
      name: 'Планка на прямых руках',
      description: 'Как обычная планка, но упор на ладони: кисти строго под плечами, руки прямые, тело — одна линия от макушки до пяток. Подтяните живот, сожмите ягодицы, не проваливайте поясницу и не поднимайте таз. Взгляд в пол. Легче классической планки на локтях — хороший вариант для начала и для отдыха между тяжёлыми сетами.',
      gifUrl: 'pending',
      type: 'strength',
      metValue: 3.5,
      muscleGroups: ['Кор', 'Плечи', 'Пресс'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 1,
      defaultDurationSec: 45,
    },
    {
      name: 'Планка с прыжками',
      description: 'Примите планку на прямых руках. Прыжком разведите ноги в стороны (как в Jumping Jacks, только в упоре) и прыжком верните обратно — корпус при этом неподвижен, таз не гуляет вверх-вниз. Приземляйтесь мягко на носки, пресс держит поясницу. Сочетает кор и кардио: отлично греет пульс в конце круга на пресс.',
      gifUrl: 'pending',
      type: 'cardio',
      metValue: 8.0,
      muscleGroups: ['Кор', 'Пресс', 'Ноги'],
      difficulty: 'intermediate',
      equipment: null,
      defaultSets: 3,
      defaultReps: 1,
      defaultDurationSec: 30,
    },
  ],

  'Кардио': [
    {
      name: 'Бег на месте',
      description: 'Бегите на месте в комфортном темпе: приземляйтесь мягко на переднюю часть стопы, колени слегка подняты, руки работают как при обычном беге. Плечи расслаблены, корпус чуть наклонён вперёд. Дышите ритмично. Хотите тяжелее — поднимайте колени выше или ускоряйтесь на 15–20 секунд с возвратом в спокойный темп.',
      gifUrl: 'https://static.wger.de/media/exercise-images/191/Running-1.png',
      type: 'cardio',
      metValue: 8.0,
      muscleGroups: ['Ноги', 'Кор'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 1,
      defaultReps: 1,
      defaultDurationSec: 600,
    },
    {
      name: 'Прыжки на скакалке',
      description: 'Отличное кардио для координации и выносливости. Сжигает много калорий.',
      gifUrl: 'https://static.wger.de/media/exercise-images/228/Jump-rope-1.png',
      type: 'cardio',
      metValue: 11.0,
      muscleGroups: ['Икры', 'Плечи', 'Кор'],
      difficulty: 'intermediate',
      equipment: 'Скакалка',
      defaultSets: 3,
      defaultReps: 1,
      defaultDurationSec: 180,
    },
    {
      name: 'Бёрпи',
      description: 'Из стойки присядьте, поставьте ладони на пол и прыжком уйдите в упор лёжа. Сделайте отжимание (можно пропустить), прыжком верните стопы к рукам и выпрыгните вверх с хлопком над головой. Приземляйтесь мягко на согнутые колени и сразу уходите в следующий повтор. Держите спину прямой при переходах — это самое энергозатратное упражнение программы, темп подбирайте по дыханию.',
      gifUrl: 'https://static.wger.de/media/exercise-images/229/Burpees-1.png',
      type: 'cardio',
      metValue: 10.0,
      muscleGroups: ['Всё тело'],
      difficulty: 'advanced',
      equipment: null,
      defaultSets: 3,
      defaultReps: 10,
    },
    {
      name: 'Jumping Jacks',
      description: 'Встаньте прямо, ноги вместе, руки вдоль тела. В прыжке разведите ноги шире плеч и одновременно поднимите прямые руки над головой; следующим прыжком вернитесь в исходное. Приземляйтесь мягко на носки, колени чуть согнуты, темп ровный и бодрый. Это разминка: цель — разогреться и поднять пульс, а не выпрыгнуть из сил.',
      gifUrl: 'https://static.wger.de/media/exercise-images/230/Jumping-jacks-1.png',
      type: 'cardio',
      metValue: 8.0,
      muscleGroups: ['Всё тело'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 30,
    },
    {
      name: 'Горные альпинисты',
      description: 'Примите упор лёжа на прямых руках, плечи над запястьями, тело — прямая линия. Поочерёдно и быстро подтягивайте колени к груди, будто бежите горизонтально. Таз не задирайте, поясницу не проваливайте, пресс держит корпус неподвижным — двигаются только ноги. Дышите часто и ровно, темп максимально быстрый, который позволяет держать форму.',
      gifUrl: 'https://static.wger.de/media/exercise-images/231/Mountain-climber-1.png',
      type: 'cardio',
      metValue: 8.0,
      muscleGroups: ['Кор', 'Квадрицепс', 'Плечи'],
      difficulty: 'intermediate',
      equipment: null,
      defaultSets: 3,
      defaultReps: 20,
    },
    {
      name: 'Высокие колени',
      description: 'Бег на месте с высоким подъёмом коленей: поочерёдно поднимайте колени до уровня пояса, помогая себе руками в беговом ритме. Спина прямая, корпус не заваливается назад, приземление мягкое на носок. Чем выше колено и быстрее темп — тем тяжелее. Отличная разминка перед днём ног.',
      gifUrl: 'https://static.wger.de/media/exercise-images/232/High-knees-1.png',
      type: 'cardio',
      metValue: 8.0,
      muscleGroups: ['Квадрицепс', 'Кор'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 30,
    },
    {
      name: 'Скалолаз',
      description: 'Упор лёжа на прямых руках. Медленно и подконтрольно подтяните колено к груди, верните ногу назад и повторите другой ногой — без прыжков и рывков, в отличие от «горных альпинистов». Корпус неподвижен, пресс напряжён, плечи над запястьями. Подходит как спокойная работа на кор, когда дыхание нужно восстановить.',
      gifUrl: 'https://static.wger.de/media/exercise-images/231/Mountain-climber-1.png',
      type: 'cardio',
      metValue: 6.0,
      muscleGroups: ['Кор', 'Ноги'],
      difficulty: 'beginner',
      equipment: null,
      defaultSets: 3,
      defaultReps: 20,
    },
  ],
};

async function seed() {
  const app = await NestFactory.createApplicationContext(AppModule);

  const categoryModel = app.get(getModelToken('WorkoutCategory'));
  const exerciseModel = app.get(getModelToken('Exercise'));

  console.log('=== Seeding workout categories ===\n');

  const categoryMap: Record<string, any> = {};
  for (const cat of categories) {
    const existing = await categoryModel.findOne({ name: cat.name });
    if (!existing) {
      const created = await categoryModel.create(cat);
      categoryMap[cat.name] = created;
      console.log(`  [+] ${cat.emoji} ${cat.name}`);
    } else {
      categoryMap[cat.name] = existing;
      console.log(`  [=] ${cat.emoji} ${cat.name} (уже существует)`);
    }
  }

  console.log('\n=== Seeding exercises ===\n');

  let createdCount = 0;
  let skippedCount = 0;

  for (const [catName, exercises] of Object.entries(exercisesByCategory)) {
    const category = categoryMap[catName];
    if (!category) continue;

    console.log(`\n  ${category.emoji} ${catName}:`);

    for (const ex of exercises) {
      const existing = await exerciseModel.findOne({ name: ex.name, categoryId: category._id });
      if (!existing) {
        await exerciseModel.create({
          ...ex,
          categoryId: category._id,
        });
        createdCount++;
        console.log(`    [+] ${ex.name} (${ex.type === 'cardio' ? 'кардио' : 'сила'}, MET ${ex.metValue})`);
      } else if (existing.description !== ex.description) {
        // the seed file is the source of truth for technique texts
        existing.description = ex.description;
        await existing.save();
        console.log(`    [~] ${ex.name} (описание обновлено)`);
      } else {
        skippedCount++;
        console.log(`    [=] ${ex.name} (уже существует)`);
      }
    }
  }

  console.log(`\n=== Готово! ===`);
  console.log(`Создано упражнений: ${createdCount}`);
  console.log(`Пропущено (уже есть): ${skippedCount}`);
  console.log(`Всего категорий: ${Object.keys(categoryMap).length}`);
  console.log(`Всего упражнений в базе: ${await exerciseModel.countDocuments()}`);

  await app.close();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
